[package]
name = "rdns-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rdns-core = { path = "../core" }
rdns-config = { path = "../config" }
clap = { version = "4.1.1", features = ["derive"] }
anyhow = "1.0.68"